/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddonsRouteImport } from './routes/addons'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as SiteRouteImport } from './routes/site'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddonsRoute = AddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/builder': typeof BuilderRoute
  '/site': typeof SiteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/builder': typeof BuilderRoute
  '/site': typeof SiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addons': typeof AddonsRoute
  '/builder': typeof BuilderRoute
  '/site': typeof SiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/addons' | '/builder' | '/site'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addons' | '/builder' | '/site'
  id: '__root__' | '/' | '/addons' | '/builder' | '/site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddonsRoute: typeof AddonsRoute
  BuilderRoute: typeof BuilderRoute
  SiteRoute: typeof SiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addons': {
      id: '/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AddonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddonsRoute: AddonsRoute,
  BuilderRoute: BuilderRoute,
  SiteRoute: SiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
